---
- name: Remove old docker versions
  apt:
    name: "{{ item }}"
    state: absent
    update_cache: yes
  with_items:
       - docker
       - docker-engine
       - docker.io

- name: Add apt-key for Docker
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add apt-key for Kubernetes
  apt_key:
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
    state: present

- name: Add Docker repository
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable
    state: present

- name: Add Kubernetes repository
  apt_repository:
    repo: deb http://apt.kubernetes.io/ kubernetes-xenial main
    state: present

- name: Install list of packages for Kubernetes
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
       - docker-ce
       - apt-transport-https
       - ca-certificates
       - curl
       - software-properties-common
       - kubelet
       - kubeadm
       - kubernetes-cni

- name: Remove swap
  lineinfile:
    path: /etc/fstab
    regexp: '^/swapfile'
    state: absent

- name: Swapoff
  command: "swapoff -a"
